### ISSUE TITLE
Add meta tags

### ISSUE THREAD

**Issue by alecive** [alecive/alecive.github.io#5]
I would like to add the following meta tags for better searchability and discovery:
- [ ] Facebook open graph http://ogp.me/
- [ ] Accelerated mobile pages https://www.ampproject.org/docs/get_started/create/basic_markup.html
- [ ] Schema.org meta data http://schema.org/
